### PR TITLE
SVG Flags

### LINKED ISSUE #60: Suggestion: svg for all flags
If you agree I'll make a PR

### PR DESCRIPTION
**Pull request by victorbnl**
Closes #60

### CODE REVIEW

**Review by VoXaN24 — APPROVED** [review]

**Comment by VoXaN24** [comment]
I can't merge for some reason that ... Wut ?

**Comment by victorbnl** [comment]
Yes it's weird I'll look at this

**Comment by victorbnl** [comment]
Maybe if you gave me the write access to the repo I could try to resolve the conflicts but if you don't want there's no problem

**Comment by victorbnl** [comment]
Try to delete `assets/images/germany.png` and `assets/images/spain.png` and merge the PR

**Comment by VoXaN24** [comment]
Work

**Pull request merged**
