### PR TITLE
Added possibility to move to next or previous track, go back to the b…

### PR DESCRIPTION
**Pull request by SexiestCHiba**
…eggining of the track if current track time < 5s or no previous track

my changes are available here: https://test.skull-pixel.fr/

### CODE REVIEW

**Comment by busybox11** [comment]
I'd like to test it. Do you have any version running on the web?
Also, is it compatible with Spotify Free?

**Comment by SexiestCHiba** [comment]
Yes check my first comment to test it (https://test.skull-pixel.fr/).
Haven't tested with Spotify Free, I'll test it now.

**Comment by SexiestCHiba** [comment]
I have tested a bit with Spotify Free, previous and next buttons work like when you're in pc app, even if you launch Spotify on phone, that delete the maximum of 6 zapped music 😂.

**Comment by busybox11** [comment]
Oh well :')
I'm merging it, thanks :)

**Pull request merged**
