### PR TITLE
Added Indonesian Language

### PR DESCRIPTION
**Pull request by HafitzSetya**

### CODE REVIEW

**Review by busybox11 — CHANGES_REQUESTED** [review]
The string `IndexCookie` is malformed, see screenshot
image

**Comment by busybox11** [comment]
Thanks anyway for your help, I really appreciate it :)

**Comment by HafitzSetya** [comment]
> The string `IndexCookie` is malformed, see screenshot
> image

Edited

**Comment by busybox11** [comment]
Thanks! I'm merging it.

I appreciate a lot your contribution!

**Pull request merged**
